// Generated by gencpp from file localization/TimestampDistance.msg
// DO NOT EDIT!


#ifndef LOCALIZATION_MESSAGE_TIMESTAMPDISTANCE_H
#define LOCALIZATION_MESSAGE_TIMESTAMPDISTANCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace localization
{
template <class ContainerAllocator>
struct TimestampDistance_
{
  typedef TimestampDistance_<ContainerAllocator> Type;

  TimestampDistance_()
    : header()
    , distance(0.0)  {
    }
  TimestampDistance_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , distance(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::localization::TimestampDistance_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::localization::TimestampDistance_<ContainerAllocator> const> ConstPtr;

}; // struct TimestampDistance_

typedef ::localization::TimestampDistance_<std::allocator<void> > TimestampDistance;

typedef boost::shared_ptr< ::localization::TimestampDistance > TimestampDistancePtr;
typedef boost::shared_ptr< ::localization::TimestampDistance const> TimestampDistanceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::localization::TimestampDistance_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::localization::TimestampDistance_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace localization

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'localization': ['/home/kaushik/ros_workspaces/drone_localization/src/localization/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::localization::TimestampDistance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::localization::TimestampDistance_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::localization::TimestampDistance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::localization::TimestampDistance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localization::TimestampDistance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localization::TimestampDistance_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::localization::TimestampDistance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4c739b0ad83c2914df6d41fe1b87d25f";
  }

  static const char* value(const ::localization::TimestampDistance_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4c739b0ad83c2914ULL;
  static const uint64_t static_value2 = 0xdf6d41fe1b87d25fULL;
};

template<class ContainerAllocator>
struct DataType< ::localization::TimestampDistance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "localization/TimestampDistance";
  }

  static const char* value(const ::localization::TimestampDistance_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::localization::TimestampDistance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 distance\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::localization::TimestampDistance_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::localization::TimestampDistance_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TimestampDistance_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::localization::TimestampDistance_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::localization::TimestampDistance_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCALIZATION_MESSAGE_TIMESTAMPDISTANCE_H
